"""add project paper relationship

Revision ID: 1bf68a745102
Revises: 42e2b507f84a
Create Date: 2026-08-24 14:44:29.928033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bf68a745102'
down_revision: Union[str, Sequence[str], None] = '42e2b507f84a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('saved_paper_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['saved_paper_id'], ['saved_papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'saved_paper_id', name='uq_project_saved_paper')
    )
    op.create_index(op.f('ix_project_papers_id'), 'project_papers', ['id'], unique=False)
    op.create_index(op.f('ix_project_papers_project_id'), 'project_papers', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_papers_saved_paper_id'), 'project_papers', ['saved_paper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_papers_saved_paper_id'), table_name='project_papers')
    op.drop_index(op.f('ix_project_papers_project_id'), table_name='project_papers')
    op.drop_index(op.f('ix_project_papers_id'), table_name='project_papers')
    op.drop_table('project_papers')
    # ### end Alembic commands ###
