"""create saved papers table

Revision ID: 42e2b507f84a
Revises: 28a387d84e79
Create Date: 2026-08-21 21:23:30.366098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e2b507f84a'
down_revision: Union[str, Sequence[str], None] = '28a387d84e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('openalex_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=500), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('paper_url', sa.String(length=2000), nullable=True),
    sa.Column('pdf_url', sa.String(length=2000), nullable=True),
    sa.Column('is_open_access', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_papers_id'), 'saved_papers', ['id'], unique=False)
    op.create_index(op.f('ix_saved_papers_openalex_id'), 'saved_papers', ['openalex_id'], unique=False)
    op.create_index(op.f('ix_saved_papers_user_id'), 'saved_papers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_papers_user_id'), table_name='saved_papers')
    op.drop_index(op.f('ix_saved_papers_openalex_id'), table_name='saved_papers')
    op.drop_index(op.f('ix_saved_papers_id'), table_name='saved_papers')
    op.drop_table('saved_papers')
    # ### end Alembic commands ###
