"""add research paper metadata

Revision ID: b92e4863f5e1
Revises: 4e33f9b3607a
Create Date: 2026-08-15 19:00:48.913545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b92e4863f5e1'
down_revision: Union[str, Sequence[str], None] = '4e33f9b3607a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('title', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('publication_year', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('journal', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('authors', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'journal')
    op.drop_column('documents', 'publication_year')
    op.drop_column('documents', 'title')
    op.drop_column('documents', 'authors')
    # ### end Alembic commands ###
